---
application:
  name: "sbrusica"
  project: "Sbrusica"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "Sbrusica-Database"
  version: "4.4"
routers:
- name: "main-sbrusica"
  routes:
  - application_name: "sbrusica"
    paths:
    - "/*"
